//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAJA
    {
        public BAJA()
        {
            this.DETALLE_BAJA = new HashSet<DETALLE_BAJA>();
            this.PARTIDA = new HashSet<PARTIDA>();
        }
    
        public decimal ID_BAJA { get; set; }
        public System.DateTime FECHA_BAJA { get; set; }
        public string MOTIVO_BAJA { get; set; }
        public string OBSERVACIONES_BAJA { get; set; }
        public decimal ESTADO_BAJA { get; set; }
    
        public virtual ICollection<DETALLE_BAJA> DETALLE_BAJA { get; set; }
        public virtual ICollection<PARTIDA> PARTIDA { get; set; }
    }
}
