//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BAJA> BAJA { get; set; }
        public DbSet<CARNET_FAMILIAR> CARNET_FAMILIAR { get; set; }
        public DbSet<COMUNA> COMUNA { get; set; }
        public DbSet<DETALLE_BAJA> DETALLE_BAJA { get; set; }
        public DbSet<DETALLE_MEDICAMENTO> DETALLE_MEDICAMENTO { get; set; }
        public DbSet<DETALLE_PARTIDA> DETALLE_PARTIDA { get; set; }
        public DbSet<DETALLE_RESERVA> DETALLE_RESERVA { get; set; }
        public DbSet<ERRORES> ERRORES { get; set; }
        public DbSet<ESTADO_RESERVA> ESTADO_RESERVA { get; set; }
        public DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public DbSet<MEDICAMENTO> MEDICAMENTO { get; set; }
        public DbSet<MEDICO> MEDICO { get; set; }
        public DbSet<MENSAJERIA> MENSAJERIA { get; set; }
        public DbSet<PACIENTE> PACIENTE { get; set; }
        public DbSet<PARTIDA> PARTIDA { get; set; }
        public DbSet<PERFIL> PERFIL { get; set; }
        public DbSet<PERSONA> PERSONA { get; set; }
        public DbSet<RECETA> RECETA { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<TUTOR> TUTOR { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
