//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_MEDICAMENTO
    {
        public decimal RECETA_ID_RECETA { get; set; }
        public int MEDICAMENTO_ID_REMEDIO { get; set; }
        public decimal CANTIDAD { get; set; }
    
        public virtual RECETA RECETA { get; set; }
        public virtual MEDICAMENTO MEDICAMENTO { get; set; }
    }
}
