//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADO_RESERVA
    {
        public ESTADO_RESERVA()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public decimal ID_ESTADO { get; set; }
        public string DESCRIPCION_ESTADO { get; set; }
    
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
