//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICAMENTO
    {
        public MEDICAMENTO()
        {
            this.DETALLE_BAJA = new HashSet<DETALLE_BAJA>();
            this.DETALLE_MEDICAMENTO = new HashSet<DETALLE_MEDICAMENTO>();
            this.DETALLE_PARTIDA = new HashSet<DETALLE_PARTIDA>();
            this.DETALLE_RESERVA = new HashSet<DETALLE_RESERVA>();
        }
    
        public int ID_REMEDIO { get; set; }
        public string NOMBRE_REMEDIO { get; set; }
        public string DESCRIPCION_REMEDIO { get; set; }
        public string FABRICANTE_REMEDIO { get; set; }
        public string TIPO_REMEDIO { get; set; }
        public string COMPONENTES_REMEDIO { get; set; }
        public string CONTENIDO_REMEDIO { get; set; }
        public short CANTCONTENIDO_REMEDIO { get; set; }
        public string UNIDADMEDIDA_REMEDIO { get; set; }
        public decimal GRAMAJE_REMEDIO { get; set; }
        public short STOCKFISICO_REMEDIO { get; set; }
        public short STOCKDIPONIBLE_REMEDIO { get; set; }
    
        public virtual ICollection<DETALLE_BAJA> DETALLE_BAJA { get; set; }
        public virtual ICollection<DETALLE_MEDICAMENTO> DETALLE_MEDICAMENTO { get; set; }
        public virtual ICollection<DETALLE_PARTIDA> DETALLE_PARTIDA { get; set; }
        public virtual ICollection<DETALLE_RESERVA> DETALLE_RESERVA { get; set; }
    }
}
