//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PARTIDA
    {
        public PARTIDA()
        {
            this.DETALLE_PARTIDA = new HashSet<DETALLE_PARTIDA>();
        }
    
        public short ID_PARTIDA { get; set; }
        public System.DateTime FECHA_PARTIDA { get; set; }
        public string TIPO_PARTIDA { get; set; }
        public decimal ESTADO_PARTIDA { get; set; }
        public decimal FUNCIONARIO_ID_FUNCIONARIO { get; set; }
        public Nullable<decimal> PACIENTE_ID_PACIENTE { get; set; }
        public Nullable<decimal> RESERVA_ID_RESERVA { get; set; }
        public Nullable<decimal> BAJA_ID_BAJA { get; set; }
    
        public virtual BAJA BAJA { get; set; }
        public virtual ICollection<DETALLE_PARTIDA> DETALLE_PARTIDA { get; set; }
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
