//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public PERSONA()
        {
            this.FUNCIONARIO = new HashSet<FUNCIONARIO>();
            this.MEDICO = new HashSet<MEDICO>();
            this.PACIENTE = new HashSet<PACIENTE>();
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public string RUT_PERSONA { get; set; }
        public string NOM_PERSONA { get; set; }
        public string APP_PERSONA { get; set; }
        public string APM_PERSONA { get; set; }
        public string FONO_PERSONA { get; set; }
        public string DIRECCION_PERSONA { get; set; }
        public System.DateTime FECNAC_PERSONA { get; set; }
        public string SEXO_PERSONA { get; set; }
        public short COMUNA_ID_COMUNA { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<FUNCIONARIO> FUNCIONARIO { get; set; }
        public virtual ICollection<MEDICO> MEDICO { get; set; }
        public virtual ICollection<PACIENTE> PACIENTE { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
