//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECETA
    {
        public RECETA()
        {
            this.DETALLE_MEDICAMENTO = new HashSet<DETALLE_MEDICAMENTO>();
        }
    
        public decimal ID_RECETA { get; set; }
        public string FRECUEN_RECETA { get; set; }
        public string DURACION_RECETA { get; set; }
        public short CANTPASTILLAS_RECETA { get; set; }
        public System.DateTime FECEMISION_RECETA { get; set; }
        public string TIPO_RECETA { get; set; }
        public decimal MEDICO_ID_MEDICO { get; set; }
        public decimal PACIENTE_ID_PACIENTE { get; set; }
        public string INDICACIONES { get; set; }
    
        public virtual ICollection<DETALLE_MEDICAMENTO> DETALLE_MEDICAMENTO { get; set; }
        public virtual MEDICO MEDICO { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
