//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public RESERVA()
        {
            this.DETALLE_RESERVA = new HashSet<DETALLE_RESERVA>();
            this.MENSAJERIA = new HashSet<MENSAJERIA>();
            this.PARTIDA = new HashSet<PARTIDA>();
        }
    
        public decimal ID_RESERVA { get; set; }
        public System.DateTime FECHA_RESERVA { get; set; }
        public decimal PACIENTE_ID_PACIENTE { get; set; }
        public decimal ESTADO_RESERVA_ID_ESTADO { get; set; }
    
        public virtual ICollection<DETALLE_RESERVA> DETALLE_RESERVA { get; set; }
        public virtual ESTADO_RESERVA ESTADO_RESERVA { get; set; }
        public virtual ICollection<MENSAJERIA> MENSAJERIA { get; set; }
        public virtual PACIENTE PACIENTE { get; set; }
        public virtual ICollection<PARTIDA> PARTIDA { get; set; }
    }
}
