//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUTOR
    {
        public string RUT_TUTOR { get; set; }
        public string NOM_TUTOR { get; set; }
        public string APP_TUTOR { get; set; }
        public string APM_TUTOR { get; set; }
        public System.DateTime FECNAC_TUTOR { get; set; }
        public string SEXO_TUTOR { get; set; }
        public Nullable<decimal> PACIENTE_ID_PACIENTE { get; set; }
    
        public virtual PACIENTE PACIENTE { get; set; }
    }
}
